# coding: utf-8

"""
    Budgets API

     The budgets API lets you manage your Brex budgets. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_budgets_python_sdk import schemas  # noqa: F401


class EmploymentStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    
A filter used to determine if a user adheres to a Budget Program.

    """
    
    @schemas.classproperty
    def ACTIVE(cls):
        return cls("EMPLOYMENT_STATUS_ACTIVE")
    
    @schemas.classproperty
    def INACTIVE(cls):
        return cls("EMPLOYMENT_STATUS_INACTIVE")
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("EMPLOYMENT_STATUS_PENDING")
