# coding: utf-8

"""
    Budgets API

     The budgets API lets you manage your Brex budgets. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_budgets_python_sdk.paths.v1_budgets_id_archive.post import ArchiveBudgetById
from brex_budgets_python_sdk.paths.v1_budgets.post import Create
from brex_budgets_python_sdk.paths.v1_budgets_id.get import GetById
from brex_budgets_python_sdk.paths.v1_budgets.get import List
from brex_budgets_python_sdk.paths.v1_budgets_id.put import UpdateBudget
from brex_budgets_python_sdk.apis.tags.budgets_api_raw import BudgetsApiRaw


class BudgetsApi(
    ArchiveBudgetById,
    Create,
    GetById,
    List,
    UpdateBudget,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BudgetsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BudgetsApiRaw(api_client)
