# coding: utf-8

"""
    Budgets API

     The budgets API lets you manage your Brex budgets. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_budgets_python_sdk.paths.v1_budgets_id_archive.post import ArchiveBudgetByIdRaw
from brex_budgets_python_sdk.paths.v1_budgets.post import CreateRaw
from brex_budgets_python_sdk.paths.v1_budgets_id.get import GetByIdRaw
from brex_budgets_python_sdk.paths.v1_budgets.get import ListRaw
from brex_budgets_python_sdk.paths.v1_budgets_id.put import UpdateBudgetRaw


class BudgetsApiRaw(
    ArchiveBudgetByIdRaw,
    CreateRaw,
    GetByIdRaw,
    ListRaw,
    UpdateBudgetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
